client.focused           #74c7ec  #1e1e2e  #cdd6f4      #74c7ec #74c7ec
client.focused_inactive  #6c7086 #1e1e2e #cdd6f4  #f5e0dc #6c7086
client.unfocused         #6c7086 #1e1e2e #cdd6f4  #f5e0dc #6c7086
client.urgent            #fab387    #1e1e2e #fab387 #6c7086  #fab387
client.placeholder       #6c7086 #1e1e2e #cdd6f4  #6c7086  #6c7086
client.background        #1e1e2e


# border
default_border pixel 1
default_floating_border pixel 1
for_window [app_id="firefox"] border none
for_window [app_id="Waydroid"] border none
for_window [instance="code"] border none
for_window [class="explorer.exe"] border none
for_window [instance="explorer.exe"] border none
for_window [title="Default - Wine desktop"] border none



# Status Bar:
# Read `man 5 sway-bar` for more information about this section.
bar {
    swaybar_command waybar
}

# GTK settings
set $gnome-schema org.gnome.desktop.interface
exec_always {
    gsettings set $gnome-schema color-scheme 'prefer-dark'
}